[package]
name = "nord_bar"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.7.3"
gtk4-layer-shell = "0.2.0"
glib-macros = "0.18.2"
gio = "0.18.3"
chrono = "0.4.31"
glib = "0.18.3"

generate-gtk = { path = "generate-gtk" }
fragile = "2.0.0"

[workspace]

[[bin]]
name = "generate-gtk"
path = "lib.rs"

