#!/bin/sh

hyprctl clients | egrep "class:|workspace:" | cut -d ':' -f 2 | grep -E -B1 [a-zA-Z]+ | cut -d ' ' -f2 |  grep "$1" -A1 | tr -d "1234567890-_" | sed "s/steamapp//g"|sed "s/steam/ /g"| sed "s/librewolf/ /g" |  sed "s/kitty/ /g" | sed "s/discord/󰙯 /g" |  sed "s/Bravebrowser/ /g" |  sed "s/.bluemanmanagerwrapped/󰂯 /g" |  sed "s/org.keepassxc.KeePassXC/ /g" |  sed "s/org.prismlauncher.PrismLauncher/󰍳 /g" | sed -e 's/[a-zA-Z]//g' | tr -d ".\n-"
